import Head from "next/head";
import Navbar from "../components/Navbar";
import About from "../components/about";
import Hero  from "../components/hero";
import Fouter from "../components/fouter";
import TimeLine from "../components/sekolah";
import From from "../components/from";


export default function Home() {
	return (
		<div>
			<Head>
				<title>Angga Puspa</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/pro.ico" />
			</Head>
			<Navbar />
      <Hero />
      <About />	
	  <TimeLine />
	  <From />
      <Fouter />
    
		</div>
	);
}